import type { GetStaticPropsContext, NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Blog.module.css'
import people from '../../contents/people.json'
import { peopleType } from '../../types'

export const getStaticPaths = async () => {
  const paths = people.list.map((p) => `/people/${p.id}`)

  return { paths, fallback: false }
}

export const getStaticProps = async (context: GetStaticPropsContext) => {
  const id = context.params?.id as string

  return {
    props: {
      peopleDetail: people.list.filter((p) => String(p.id) === id)[0],
    },
  }
}

type Props = {
  peopleDetail: peopleType
}

const PeopleDetail: NextPage<Props> = ({ peopleDetail }) => {
  return (
    <>
      <Head>
        <title>{peopleDetail.name} | People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1>{peopleDetail.name}</h1>
        <p>id: {peopleDetail.id}</p>
        <p>age: {peopleDetail.age}</p>
        <p>branch: {peopleDetail.branch}</p>
      </div>
    </>
  )
}

export default PeopleDetail
