import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Blog.module.css'
import people from '../../contents/people.json'
import { peopleType } from '../../types'
import Link from 'next/link'

export const getStaticProps = async () => {
  return {
    props: {
      people: people.list,
    },
  }
}

type Props = {
  people: peopleType[]
}

const People: NextPage<Props> = ({ people }) => {
  return (
    <>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1>People</h1>
        <ul>
          {people && people.map((p) => {
            return (
              <li key={p.id}>
                <Link href={`/people/${p.id}`}>
                  <a>{p.name}</a>
                </Link>
              </li>
            )
          })}
        </ul>
      </div>
    </>
  )
}

export default People
