import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Blog.module.css'

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1>Blog</h1>
      </div>
    </>
  )
}

export default Blog
