name: Deploy to Amazon S3

on:
  push: # push時に作動
    branches: [main] # main ブランチが対象

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # ソースコードのチェックアウト
        uses: actions/checkout@v2

      - name: Setup Node # Node 環境のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Export
        run: yarn export

      - name: Deploy
        run: echo "deploy!"
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      #   run: aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_NAME }}