name: Deploy to AWS S3

on:
  workflow_dispatch:
  push: # push時に作動
    branches: [main] # main ブランチが対象

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Node.jsのバージョンを確認
        run: node -v
      - name: Npmのバージョンを確認
        run: npm -v
      - name: Yarnのバージョンを確認
        run: yarn -v

  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: say hello!
        run: echo "hello!"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # ソースコードのチェックアウト。リポジトリ内のファイルにアクセスする
        uses: actions/checkout@v2

      - name: Setup Node # Node 環境のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies # 依存モジュールをインストール
        run: yarn install

      - name: Export # ビルド & 静的ファイルエクスポート
        run: yarn export

      - name: Deploy # デプロイ実行
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 ./dist s3://${{ secrets.AWS_BUCKET_NAME}} --delete

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./dist